apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: yooncount/demo-backend:5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
