apiVersion: v1
kind: Service
metadata:
  name: demo-backend-svc
spec:
  type: NodePort
  selector:
    app: demo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
